/**
 * =======================================================================
 * 🐾 에스앤제이 동물병원 (Dr. S & J Animal Hospital)
 * ORCA 5-Agent Tournament Champion Client Engine v3.0
 * 
 * - VETAZE 3.0 스마트 임상 트리아지 엔진 (원터치 4-Step + 키워드 온톨로지)
 * - 수의 임상 SOAP 차트 자동 연동 (Subjective, Objective, Assessment, Plan)
 * - 파보겔(Parvogel) 500ml 대용량 겔 실시간 체중별 용량 계산기
 * - B2B 수요일 경매장 픽업 사전 발주 패키지 프리셋 (원클릭 카트 & 폴백 전송)
 * - 순수 독립 프론트엔드 (0-Server Fallback, LocalStorage 백업, A4 1장 인쇄 엔진)
 * =======================================================================
 */

// 1. 이중 타겟 퀵 스위처 (일반 보호자 문진 vs 경매장 B2B 픽업)
let currentAudienceMode = 'b2c';
function switchAudienceMode(mode) {
  currentAudienceMode = mode;
  const tabB2C = document.getElementById('tabB2C');
  const tabB2B = document.getElementById('tabB2B');

  if (mode === 'b2b') {
    if (tabB2C) { tabB2C.classList.remove('active'); tabB2C.setAttribute('aria-selected', 'false'); }
    if (tabB2B) { tabB2B.classList.add('active'); tabB2B.setAttribute('aria-selected', 'true'); }
    const target = document.getElementById('b2b-hub');
    if (target) target.scrollIntoView({ behavior: 'smooth' });
  } else {
    if (tabB2B) { tabB2B.classList.remove('active'); tabB2B.setAttribute('aria-selected', 'false'); }
    if (tabB2C) { tabB2C.classList.add('active'); tabB2C.setAttribute('aria-selected', 'true'); }
    focusTriageInput();
  }
}

// 2. VETAZE 3.0 트리아지 4단계 인터랙티브 스텝 상태 관리
const triageStepState = {
  age: 'puppy',        // 'puppy' (~2개월) | 'junior' (3~5개월) | 'adult' (6개월 이상)
  stool: 'soft',       // 'normal' | 'soft' | 'diarrhea' | 'bloody'
  vomit: 'yellow1',    // 'none' | 'yellow1' | 'repeat' | 'foam_blood'
  vital: 'normal'      // 'normal' | 'lethargic' | 'collapse'
};

const STEP_LABELS = {
  age: { puppy: '생후 ~2개월(고위험)', junior: '3~5개월(면역형성)', adult: '6개월 이상' },
  stool: { normal: '정상변', soft: '묽은변(연변)', diarrhea: '점액·물설사', bloody: '혈변(악취)' },
  vomit: { none: '구토없음', yellow1: '1회 노란토', repeat: '2회 이상 반복구토', foam_blood: '거품/혈성구토' },
  vital: { normal: '정상활력', lethargic: '기운없음/식욕부진', collapse: '완전처짐/저체온' }
};

function selectTriageStep(category, value, buttonEl) {
  triageStepState[category] = value;
  
  // 버튼 UI 상태 갱신
  if (buttonEl && buttonEl.parentElement) {
    const siblings = buttonEl.parentElement.querySelectorAll('.step-btn');
    siblings.forEach(btn => {
      btn.classList.remove('selected', 'danger-selected');
    });
    if (value === 'bloody' || value === 'foam_blood' || value === 'collapse') {
      buttonEl.classList.add('danger-selected');
    } else {
      buttonEl.classList.add('selected');
    }
  }

  // 실시간 텍스트 제안 반영
  const inputEl = document.getElementById('symptomText');
  if (inputEl && (!inputEl.value || inputEl.dataset.autoGenerated === 'true')) {
    const ageDesc = STEP_LABELS.age[triageStepState.age];
    const stoolDesc = STEP_LABELS.stool[triageStepState.stool];
    const vomitDesc = STEP_LABELS.vomit[triageStepState.vomit];
    const vitalDesc = STEP_LABELS.vital[triageStepState.vital];
    inputEl.value = `[${ageDesc}] 배변: ${stoolDesc}, 구토: ${vomitDesc}, 활력: ${vitalDesc}.`;
    inputEl.dataset.autoGenerated = 'true';
  }

  // 실시간 빠른 사전 판정 (게이지 즉각 연동)
  evaluateTriage(false);
}

// 3. 증상 빠른 칩 적용 & 입력창 포커스
function applyChip(text) {
  const textarea = document.getElementById('symptomText');
  if (textarea) {
    textarea.value = text;
    textarea.dataset.autoGenerated = 'false';
    textarea.focus();
    evaluateTriage(true);
  }
}

function focusTriageInput() {
  const area = document.getElementById('triage');
  if (area) {
    area.scrollIntoView({ behavior: 'smooth' });
    const input = document.getElementById('symptomText');
    if (input) input.focus();
  }
}

// 4. VETAZE 3.0 종합 수의 AI 트리아지 판정 엔진
let isTriageRunning = false;
function runSmartTriage() {
  evaluateTriage(true);
}

function evaluateTriage(showLoader) {
  if (isTriageRunning) return;
  const inputEl = document.getElementById('symptomText');
  const text = inputEl ? inputEl.value.trim() : '';
  const loader = document.getElementById('triageLoader');
  const loaderText = document.getElementById('triageLoaderText');
  const resultArea = document.getElementById('triageResultArea');
  const pill = document.getElementById('resultStatusPill');
  const heading = document.getElementById('resultHeading');
  const guide = document.getElementById('resultActionGuide');
  const meterPin = document.getElementById('triageMeterPin');
  const meterRiskText = document.getElementById('meterRiskText');
  const actionPills = document.getElementById('triageActionPills');

  if (!text && !showLoader) return;

  if (showLoader) {
    isTriageRunning = true;
    if (resultArea) resultArea.style.display = 'none';
    if (loader) loader.classList.add('active');
    if (loaderText) loaderText.innerText = '반려견 임상 온톨로지 키워드 및 생체 지표 분석 중...';

    setTimeout(() => {
      if (loaderText) loaderText.innerText = '5,000여 건 수의 임상 데이터베이스 & 소화기 프로토콜 매칭 중...';
    }, 250);
  }

  const finalize = () => {
    if (loader) loader.classList.remove('active');
    isTriageRunning = false;
    if (resultArea) resultArea.style.display = 'block';

    const t = text.toLowerCase();
    let grade = 'GREEN';
    let pinLeft = '12%';
    let riskDesc = '1단계 안정 (GREEN)';
    let headTitle = '현재 즉각적인 급성 위험 신호는 감지되지 않았습니다';
    let actionDesc = '아이의 활력과 음수량을 평소대로 유지해 주시고, 12시간 이상 관찰 후 이상 증상이 나타날 경우 언제든 재문진해 주세요.';
    let pillsHtml = '<span class="t-pill t-pill-care">💧 평소 음수량 유지</span><span class="t-pill t-pill-care">🌡️ 체온 및 배변 상태 관찰</span>';
    
    // SOAP 차트용 임상 데이터
    let soapAssessment = '단순 소화기 불편 또는 환경 변화 스트레스 (경과 관찰 가능)';
    let soapPlan = '· 평소 사료 급여 유지 및 배변/구토 12시간 모니터링\n· 증상 지속 시 수의사 유선 상담 (031-321-6562)';

    const isRedRisk = (
      triageStepState.stool === 'bloody' ||
      triageStepState.vomit === 'foam_blood' ||
      triageStepState.vital === 'collapse' ||
      t.includes('혈변') || t.includes('피똥') || t.includes('경련') || t.includes('발작') || 
      t.includes('호흡') || t.includes('숨') || t.includes('헐떡') || t.includes('의식') || 
      t.includes('쓰러') || t.includes('저체온')
    );

    const isOrangeRisk = (
      triageStepState.stool === 'diarrhea' ||
      triageStepState.vomit === 'repeat' ||
      (triageStepState.age === 'puppy' && triageStepState.stool === 'soft') ||
      t.includes('구토') || t.includes('토') || t.includes('설사') || t.includes('물변') || 
      t.includes('점액') || t.includes('처져') || t.includes('무기력') || t.includes('탈수') ||
      t.includes('기침') || t.includes('켁켁') || t.includes('가래') || t.includes('콧물')
    );

    const isYellowRisk = (
      triageStepState.stool === 'soft' ||
      triageStepState.vomit === 'yellow1' ||
      triageStepState.vital === 'lethargic' ||
      t.includes('안 먹') || t.includes('식욕') || t.includes('기운') || t.includes('사료 거부') ||
      t.includes('가려') || t.includes('귀') || t.includes('털') || t.includes('비듬')
    );

    // 1) 초응급 (RED) : 골든타임 사수
    if (isRedRisk) {
      grade = 'RED';
      pinLeft = '93%';
      riskDesc = '4단계 초응급 (RED : 즉시 응급센터 내원)';
      if (pill) {
        pill.className = 'triage-status-pill status-red';
        pill.innerHTML = '<span>🔴 RED : 즉시 응급 내원 필요 (골든타임)</span>';
      }
      headTitle = '파보바이러스 장염, 패혈증 또는 급성 저혈당·탈수 쇼크 고위험';
      actionDesc = '· <strong>즉각 조치:</strong> 추가 사료 및 약물 강제 급여를 즉시 중단하시고 보온을 유지하며 즉시 에스앤제이 동물병원 또는 24시 응급센터로 내원하십시오.<br />· <strong>임상 프로토콜:</strong> CPV 파보 신속키트 검사, 혈당 측정 및 정맥 수액 처치가 시급합니다.';
      pillsHtml = '<span class="t-pill t-pill-med">⚠️ 사료/물 급여 즉각 중단</span><span class="t-pill t-pill-kit">🔬 CPV 신속 진단키트 필수</span><span class="t-pill t-pill-med">🏥 정맥 수액 & 항체 집중치료</span>';
      soapAssessment = '파보바이러스 장염(CPV) 의심, 급성 출혈성 위장염(HGE), 저혈당·탈수 쇼크 고위험';
      soapPlan = '· CPV/CCV 신속 항원 진단키트 즉각 실시\n· 정맥 라인 확보 및 전해질/포도당 수액 처치\n· 파보겔 500ml 장점막 물리적 코팅 및 2차 감염 방지 항생제 조제';
    } 
    // 2) 경고 및 당일 내원 (ORANGE) : 소화기/호흡기 집중 케어
    else if (isOrangeRisk) {
      grade = 'ORANGE';
      pinLeft = '68%';
      riskDesc = '3단계 경고 (ORANGE : 당일 내원 권고)';
      if (pill) {
        pill.className = 'triage-status-pill status-orange';
        pill.innerHTML = '<span>🟠 ORANGE : 오늘 중 동물병원 방문 권고</span>';
      }
      headTitle = '급성 장염 또는 바이러스성 소화기 감염증 의심';
      actionDesc = '· <strong>임상 조치:</strong> 자견의 경우 2~3회 설사만으로도 전해질 불균형과 탈수가 빠르게 진행됩니다. 미온수로 입술을 축여주시고 원내로 내원하십시오.<br />· <strong>권장 처방:</strong> <strong>파보겔(Parvogel) 500ml</strong> 장 점막 흡착·코팅 겔 투약 및 파보·코로나 진단키트 검사가 권장됩니다.';
      pillsHtml = '<span class="t-pill t-pill-kit">🔬 CPV/CCV 신속진단키트</span><span class="t-pill t-pill-med">💊 파보겔 500ml 장점막 코팅</span><span class="t-pill t-pill-care">💧 미온수 소량 축이기</span>';
      soapAssessment = '급성 소화기 감염증 또는 식이성 장염 의심 (자견 탈수 및 장점막 손상 주의)';
      soapPlan = '· CPV/CCV 신속진단키트 검사 병행\n· 파보겔 500ml 1회 1.0~1.5ml/kg 급여 (타약제와 1~2시간 분리)\n· 미온수 보충 및 체온 보온 관리';
    }
    // 3) 주의 및 외래 상담 (YELLOW) : 경증 관찰 및 약제 상담
    else if (isYellowRisk) {
      grade = 'YELLOW';
      pinLeft = '38%';
      riskDesc = '2단계 상담 (YELLOW : 외래 진료 및 복약)';
      if (pill) {
        pill.className = 'triage-status-pill status-yellow';
        pill.innerHTML = '<span>🟡 YELLOW : 수의사 유선 상담 및 12시간 경과 관찰</span>';
      }
      headTitle = '환경 변화 스트레스 또는 초기 소화기 불편 신호';
      actionDesc = '· <strong>모니터링:</strong> 사료를 미온수에 불려 소량 급여해 보시고, 12시간 이상 거부 시 저혈당 방지를 위해 진료실로 문의하십시오.';
      pillsHtml = '<span class="t-pill t-pill-care">🥣 미온수에 불린 사료 급여</span><span class="t-pill t-pill-med">💊 파보겔 장점막 안정 투약</span><span class="t-pill t-pill-care">⏱️ 12시간 모니터링</span>';
      soapAssessment = '환경 적응 스트레스성 연변 또는 경미한 소화불량';
      soapPlan = '· 사료 불림 소량 급여 및 12시간 경과 관찰\n· 무른변 지속 시 파보겔 500ml 급여 및 진단키트 스크리닝';
    } else {
      if (pill) {
        pill.className = 'triage-status-pill status-green';
        pill.innerHTML = '<span>🟢 GREEN : 자택 내 안정 및 일상 관찰 가능</span>';
      }
    }

    if (heading) heading.innerText = headTitle;
    if (guide) guide.innerHTML = actionDesc;
    if (meterPin) meterPin.style.left = pinLeft;
    if (meterRiskText) {
      meterRiskText.innerText = riskDesc;
      meterRiskText.style.color = grade === 'RED' ? '#b91c1c' : grade === 'ORANGE' ? '#c2410c' : grade === 'YELLOW' ? '#854d0e' : '#15803d';
    }
    if (actionPills) actionPills.innerHTML = pillsHtml;

    // 요약서 입력 폼 및 SOAP 차트 동기화
    const symInput = document.getElementById('summarySymptoms');
    if (symInput) symInput.value = text || headTitle;
    const chartTriageBadge = document.getElementById('chartTriageBadge');
    if (chartTriageBadge) {
      chartTriageBadge.innerText = `트리아지: ${riskDesc}`;
      chartTriageBadge.style.background = grade === 'RED' ? '#fee2e2' : grade === 'ORANGE' ? '#ffedd5' : grade === 'YELLOW' ? '#fef9c3' : '#dcfce7';
      chartTriageBadge.style.color = grade === 'RED' ? '#b91c1c' : grade === 'ORANGE' ? '#c2410c' : grade === 'YELLOW' ? '#854d0e' : '#15803d';
    }

    // 전역 SOAP 상태 캐시
    window._lastSOAP = {
      riskDesc,
      grade,
      headTitle,
      soapAssessment,
      soapPlan
    };

    syncChartPreview();

    if (showLoader) {
      resultArea.setAttribute('tabindex', '-1');
      resultArea.focus({ preventScroll: true });
      resultArea.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }
  };

  if (showLoader) {
    setTimeout(finalize, 550);
  } else {
    finalize();
  }
}

// 5. 트리아지 결과를 진료실 한 장 요약서로 원클릭 전송
function transferTriageToSummary() {
  syncChartPreview();
  openModal('summaryModal');
}

// 6. 파보겔 체중별 1회 권장량 계산기 (kg당 1.0~1.5ml)
function calculateDosage() {
  const weightInput = document.getElementById('petWeight');
  const calcResult = document.getElementById('calcResult');
  if (!weightInput || !calcResult) return;

  const weight = parseFloat(weightInput.value);
  if (isNaN(weight) || weight <= 0) {
    calcResult.innerText = '체중을 올바르게 입력해 주세요';
    return;
  }

  const minDose = (weight * 1.0).toFixed(1);
  const maxDose = (weight * 1.5).toFixed(1);
  calcResult.innerText = `약 ${minDose} ~ ${maxDose} ml (눈금 주사기 또는 펌핑)`;
}

function selectWeightChip(val) {
  const weightInput = document.getElementById('petWeight');
  if (weightInput) {
    weightInput.value = val;
    calculateDosage();
  }
  document.querySelectorAll('.weight-chip-btn').forEach(btn => {
    if (parseFloat(btn.innerText) === val) {
      btn.classList.add('active');
    } else {
      btn.classList.remove('active');
    }
  });
}

// 7. 진료실 요약서 SOAP 임상 차트 프리뷰 동기화
function syncChartPreview() {
  const petEl = document.getElementById('summaryPetName');
  const infoEl = document.getElementById('summaryPetInfo');
  const symEl = document.getElementById('summarySymptoms');
  const qEl = document.getElementById('summaryQuestion');

  const chartPetName = document.getElementById('chartPetName');
  const chartPetInfo = document.getElementById('chartPetInfo');
  const chartSymptoms = document.getElementById('chartSymptoms');
  const chartObjective = document.getElementById('chartObjective');
  const chartAssessment = document.getElementById('chartAssessment');
  const chartPlan = document.getElementById('chartPlan');
  const chartQuestion = document.getElementById('chartQuestion');
  const chartDate = document.getElementById('chartDate');

  if (chartPetName && petEl) chartPetName.innerText = petEl.value || '미입력';
  if (chartPetInfo && infoEl) chartPetInfo.innerText = infoEl.value || '미입력';
  if (chartSymptoms && symEl) chartSymptoms.innerText = symEl.value || '특이 증상 없음';
  if (chartQuestion && qEl) chartQuestion.innerText = qEl.value || '특이 질문 없음';

  if (chartObjective) {
    const age = STEP_LABELS.age[triageStepState.age] || '미선택';
    const stool = STEP_LABELS.stool[triageStepState.stool] || '미선택';
    const vomit = STEP_LABELS.vomit[triageStepState.vomit] || '미선택';
    const vital = STEP_LABELS.vital[triageStepState.vital] || '미선택';
    chartObjective.innerText = `· 연령: ${age} | 배변: ${stool} | 구토: ${vomit} | 활력: ${vital}`;
  }

  if (window._lastSOAP) {
    if (chartAssessment) chartAssessment.innerText = window._lastSOAP.soapAssessment;
    if (chartPlan) chartPlan.innerHTML = window._lastSOAP.soapPlan.replace(/\n/g, '<br />');
  }

  if (chartDate) {
    chartDate.innerText = new Date().toLocaleDateString('ko-KR', { year: 'numeric', month: '2-digit', day: '2-digit' });
  }
}

// 8. B2B 현장 픽업 사전 발주 추천 패키지 프리셋 (A, B, C)
function selectPresetPackage(pkg) {
  const pv = document.getElementById('itemParvogel');
  const qPv = document.getElementById('qtyParvogel');
  const pKit = document.getElementById('itemParvoKit');
  const qPKit = document.getElementById('qtyParvoKit');
  const cKit = document.getElementById('itemCoronaKit');
  const qCKit = document.getElementById('qtyCoronaKit');
  const cbKit = document.getElementById('itemComboKit');
  const qCbKit = document.getElementById('qtyComboKit');
  const bKit = document.getElementById('itemBrucellaKit');
  const qBKit = document.getElementById('qtyBrucellaKit');
  const rx = document.getElementById('itemRxMeds');
  const memo = document.getElementById('orderMemo');

  // 전체 리셋
  if (pv) pv.checked = false;
  if (pKit) pKit.checked = false;
  if (cKit) cKit.checked = false;
  if (cbKit) cbKit.checked = false;
  if (bKit) bKit.checked = false;
  if (rx) rx.checked = false;

  if (pkg === 'packageA' || pkg === 1) {
    if (pv) { pv.checked = true; if (qPv) qPv.value = 2; }
    if (pKit) { pKit.checked = true; if (qPKit) qPKit.value = 1; }
    if (cKit) { cKit.checked = true; if (qCKit) qCKit.value = 1; }
    if (memo) memo.value = '[PACK A 신생 자견 입고 안심팩] 이번 주 수요일 현장 진료실 픽업 희망합니다.';
  } else if (pkg === 'packageB' || pkg === 2) {
    if (pv) { pv.checked = true; if (qPv) qPv.value = 3; }
    if (cbKit) { cbKit.checked = true; if (qCbKit) qCbKit.value = 2; }
    if (rx) rx.checked = true;
    if (memo) memo.value = '[PACK B 경매 낙찰 즉시 처치팩] 이번 주 수요일 현장 진료실 픽업 희망합니다.';
  } else if (pkg === 'packageC' || pkg === 3) {
    if (pv) { pv.checked = true; if (qPv) qPv.value = 5; }
    if (cbKit) { cbKit.checked = true; if (qCbKit) qCbKit.value = 3; }
    if (bKit) { bKit.checked = true; if (qBKit) qBKit.value = 2; }
    if (memo) memo.value = '[PACK C 대규모 켄넬 상비 번들] 이번 주 수요일 현장 진료실 픽업 희망합니다.';
  }

  openOrderModal();
}

// 9. B2B 수요일 현장 수령 사전 발주 처리 (안정형 폴백 시스템)
function handlePreOrderSubmit(e) {
  e.preventDefault();
  const compEl = document.getElementById('orderCompany');
  const phoneEl = document.getElementById('orderPhone');
  const memoEl = document.getElementById('orderMemo');
  const comp = compEl ? compEl.value.trim() : '';
  const phone = phoneEl ? phoneEl.value.trim() : '';
  const memo = memoEl ? memoEl.value.trim() : '';

  if (!comp || !phone) { alert('상호명과 연락처를 입력해주세요.'); return; }
  const phonePat = /^01[0-9]-?[0-9]{3,4}-?[0-9]{4}$/;
  if (!phonePat.test(phone.replace(/\s/g, ''))) {
    if (!confirm('연락처 형식이 올바르지 않을 수 있습니다. 그대로 접수할까요?\n입력값: ' + phone)) return;
  }

  let items = [];
  const checks = [
    ['itemParvogel', 'qtyParvogel', '파보겔 500ml ', '개'],
    ['itemParvoKit', 'qtyParvoKit', '파보키트(10T) ', '박스'],
    ['itemCoronaKit', 'qtyCoronaKit', '코로나키트(10T) ', '박스'],
    ['itemComboKit', 'qtyComboKit', '파보+코로나콤보(10T) ', '박스'],
    ['itemBrucellaKit', 'qtyBrucellaKit', '브루셀라키트(10T) ', '박스'],
  ];

  checks.forEach(([chkId, qtyId, pre, suf]) => {
    const chk = document.getElementById(chkId);
    const qty = document.getElementById(qtyId);
    if (chk && chk.checked) items.push(pre + (qty ? qty.value : '1') + suf);
  });

  if (document.getElementById('itemRxMeds') && document.getElementById('itemRxMeds').checked) {
    items.push('원내 처방약(파보겔 외 소화기·호흡기/소염제)');
  }

  if (items.length === 0) { alert('주문할 품목을 1개 이상 선택해주세요.'); return; }

  const orderText = `[에스앤제이 수요일 현장수령 사전발주]\n· 상호명: ${comp}\n· 연락처: ${phone}\n· 신청품목: ${items.join(', ')}\n· 메모: ${memo}\n· 접수시간: ${new Date().toLocaleString('ko-KR')}\n· 수령장소: 경기도 용인시 처인구 포곡읍 선장1로 98-8 (봄봄솔루션 경매장 내 에스앤제이 진료실)`;

  // 1) 로컬 저장 (최근 20건 보존)
  try {
    const hist = JSON.parse(localStorage.getItem('snj_orders') || '[]');
    hist.push({ comp, phone, items: items.join(', '), memo, at: new Date().toISOString(), orderText });
    localStorage.setItem('snj_orders', JSON.stringify(hist.slice(-20)));
  } catch (err) {}

  // 2) 클립보드 복사
  if (navigator.clipboard && navigator.clipboard.writeText) {
    navigator.clipboard.writeText(orderText).catch(() => {});
  }

  // 3) 선택적 엔드포인트 서버 전송
  const endpoint = (window.HOSPITAL_CONFIG && window.HOSPITAL_CONFIG.orderEndpoint) || '';
  let endpointPromise = Promise.resolve('local');
  if (endpoint) {
    endpointPromise = fetch(endpoint, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ comp, phone, items, memo, orderText })
    }).then(r => r.ok ? 'server-ok' : 'server-fail').catch(() => 'server-fail');
  }

  // 4) 성공 모달 출력
  closeModal('orderModal');
  endpointPromise.then(status => {
    showOrderSuccess(orderText, status);
  });
}

function showOrderSuccess(orderText, serverStatus) {
  const modal = document.getElementById('orderSuccessModal');
  const pre = document.getElementById('orderSuccessText');
  const badge = document.getElementById('orderSuccessBadge');
  if (pre) pre.textContent = orderText;
  if (badge) {
    if (serverStatus === 'server-ok') {
      badge.textContent = '✅ 서버 전송 완료';
      badge.style.background = '#dcfce7';
      badge.style.color = '#15803d';
    } else if (serverStatus === 'server-fail') {
      badge.textContent = '⚠️ 서버 전송 실패 · 로컬 저장됨';
      badge.style.background = '#fee2e2';
      badge.style.color = '#b91c1c';
    } else {
      badge.textContent = '📋 로컬 저장 + 클립보드 복사 완료';
      badge.style.background = '#e0f2fe';
      badge.style.color = '#0369a1';
    }
  }
  if (modal) openModal('orderSuccessModal');
}

function shareOrderText() {
  const t = document.getElementById('orderSuccessText');
  const txt = t ? t.textContent : '';
  if (navigator.share) {
    navigator.share({ title: '에스앤제이 동물병원 사전발주', text: txt }).catch(() => {});
  } else if (navigator.clipboard) {
    navigator.clipboard.writeText(txt).then(() => alert('발주서 텍스트가 클립보드에 복사되었습니다.')).catch(() => {});
  }
}

function openOrderModal() { openModal('orderModal'); }

// 10. 모달 제어 (접근성: 포커스 트랩 및 키보드 Escape)
function openModal(modalId) {
  const modal = document.getElementById(modalId);
  if (!modal) return;
  modal.style.display = 'flex';
  const focusable = modal.querySelectorAll('button, [href], input, select, textarea, [tabindex]:not([tabindex="-1"])');
  if (focusable.length) focusable[0].focus();
  document.body.style.overflow = 'hidden';
}

function closeModal(modalId) {
  const modal = document.getElementById(modalId);
  if (!modal) return;
  modal.style.display = 'none';
  document.body.style.overflow = '';
}

window.addEventListener('click', function(event) {
  if (event.target.classList.contains('modal-backdrop')) {
    event.target.style.display = 'none';
    document.body.style.overflow = '';
  }
});

window.addEventListener('keydown', function(event) {
  if (event.key === 'Escape') {
    document.querySelectorAll('.modal-backdrop').forEach(function(modal) {
      if (modal.style.display === 'flex') {
        modal.style.display = 'none';
        document.body.style.overflow = '';
      }
    });
    closeMobileMenu();
  }
});

// 11. 모바일 햄버거 메뉴
function toggleMobileMenu() {
  const btn = document.getElementById('mobileMenuBtn');
  const nav = document.getElementById('mobileNav');
  if (!btn || !nav) return;
  const expanded = btn.getAttribute('aria-expanded') === 'true';
  btn.setAttribute('aria-expanded', String(!expanded));
  btn.setAttribute('aria-label', !expanded ? '메뉴 닫기' : '메뉴 열기');
  if (expanded) {
    nav.hidden = true;
    document.body.style.overflow = '';
  } else {
    nav.hidden = false;
    const firstA = nav.querySelector('a');
    if (firstA) firstA.focus();
    document.body.style.overflow = 'hidden';
  }
}

function closeMobileMenu() {
  const btn = document.getElementById('mobileMenuBtn');
  const nav = document.getElementById('mobileNav');
  if (!btn || !nav || nav.hidden) return;
  btn.setAttribute('aria-expanded', 'false');
  btn.setAttribute('aria-label', '메뉴 열기');
  nav.hidden = true;
  document.body.style.overflow = '';
  btn.focus();
}

// 12. A4 진료실 SOAP 차트 인쇄 엔진 (A4 1장 전용 팝업)
function escHtml(str) {
  return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

function printSummary() {
  const petRaw = document.getElementById('summaryPetName').value || '미입력';
  const infoRaw = document.getElementById('summaryPetInfo').value || '미입력';
  const symRaw = document.getElementById('summarySymptoms').value || '특이사항 없음';
  const qRaw = document.getElementById('summaryQuestion').value || '특이사항 없음';
  const todayRaw = new Date().toLocaleDateString('ko-KR', { year: 'numeric', month: 'long', day: 'numeric' });

  const age = STEP_LABELS.age[triageStepState.age];
  const stool = STEP_LABELS.stool[triageStepState.stool];
  const vomit = STEP_LABELS.vomit[triageStepState.vomit];
  const vital = STEP_LABELS.vital[triageStepState.vital];
  const risk = (window._lastSOAP && window._lastSOAP.riskDesc) || '3단계 경고 (ORANGE)';
  const assess = (window._lastSOAP && window._lastSOAP.soapAssessment) || '급성 소화기 감염증 또는 식이성 장염 의심';
  const plan = (window._lastSOAP && window._lastSOAP.soapPlan) || '· CPV/CCV 신속진단키트 검사 병행\n· 파보겔 500ml 장점막 흡착 코팅 투약';

  const pet = escHtml(petRaw);
  const info = escHtml(infoRaw);
  const sym = escHtml(symRaw);
  const q = escHtml(qRaw);
  const today = escHtml(todayRaw);

  const printHtml = `
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <title>에스앤제이 동물병원 - 수의 임상 사전 문진 차트 (SOAP)</title>
  <style>
    @page { size: A4 portrait; margin: 12mm 15mm; }
    * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, "Pretendard", sans-serif; }
    body { background: #fff; color: #0f172a; padding: 10px; font-size: 13px; line-height: 1.5; }
    .sheet { max-width: 720px; margin: 0 auto; border: 2px solid #0d9488; border-radius: 12px; padding: 24px 28px; }
    .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #0d9488; padding-bottom: 12px; margin-bottom: 16px; }
    .h-title { font-size: 21px; font-weight: 900; color: #132e47; }
    .h-sub { font-size: 12px; color: #0d9488; font-weight: 700; margin-top: 3px; }
    .h-right { text-align: right; font-size: 11px; color: #64748b; }
    .meta-box { font-size: 10.5px; color: #475569; margin-top: 4px; line-height: 1.4; }
    
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin-bottom: 12px; }
    .field-box { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 8px 12px; }
    .label { font-size: 10px; font-weight: 800; color: #64748b; text-transform: uppercase; margin-bottom: 2px; }
    .value { font-size: 14px; font-weight: 800; color: #0f172a; }

    .soap-box { margin-bottom: 10px; border: 1px solid #cbd5e1; border-radius: 6px; overflow: hidden; }
    .soap-head { background: #f1f5f9; padding: 5px 10px; font-size: 11px; font-weight: 800; color: #1e293b; border-bottom: 1px solid #cbd5e1; display: flex; justify-content: space-between; }
    .soap-body { padding: 8px 10px; font-size: 12.5px; line-height: 1.5; color: #0f172a; white-space: pre-wrap; }

    .callout { background: #f0fdfa; border: 1px solid #99f6e4; border-radius: 6px; padding: 8px 12px; font-size: 11.5px; color: #0f766e; margin-bottom: 12px; }
    .footer { margin-top: 18px; padding-top: 10px; border-top: 1px dashed #94a3b8; display: flex; justify-content: space-between; align-items: center; font-size: 11px; color: #64748b; }
    .sign-area { display: flex; align-items: center; gap: 14px; }
    .sign-stamp { width: 65px; height: 35px; border: 1px dashed #cbd5e1; display: flex; align-items: center; justify-content: center; font-size: 10px; color: #94a3b8; border-radius: 4px; }
  </style>
</head>
<body>
  <div class="sheet">
    <div class="header">
      <div>
        <div class="h-title">📋 에스앤제이 동물병원 사전 문진 임상 차트</div>
        <div class="h-sub">DR. S &amp; J ANIMAL HOSPITAL · 전문 진료센터 (용인시 처인구 개설 제5620000-010-2025-0002호)</div>
        <div class="meta-box">원장 홍순일(면허 제5374호) · 진료수의사 성하정(면허 제5398호) | 031-321-6562</div>
      </div>
      <div class="h-right">
        <div>접수일자: <strong>${today}</strong></div>
        <div style="font-weight:800; color:#c2410c; margin-top:3px; background:#ffedd5; padding:2px 6px; border-radius:4px;">${risk}</div>
      </div>
    </div>

    <div class="grid">
      <div class="field-box">
        <div class="label">환견 성명 (Patient)</div>
        <div class="value">${pet}</div>
      </div>
      <div class="field-box">
        <div class="label">품종 / 연령 / 체중</div>
        <div class="value">${info}</div>
      </div>
    </div>

    <!-- SOAP [S] -->
    <div class="soap-box">
      <div class="soap-head">
        <span>[S] 보호자 주호소 및 발생 경위 (Subjective History)</span>
        <span style="color:#64748b;">보호자 직접 서술</span>
      </div>
      <div class="soap-body">${sym}</div>
    </div>

    <!-- SOAP [O] -->
    <div class="soap-box">
      <div class="soap-head">
        <span>[O] 사전 문진 객관 지표 (Objective Triage Metrics)</span>
        <span style="color:#0d9488;">VETAZE 3.0 임상 지표</span>
      </div>
      <div class="soap-body">· 월령 구분: <strong>${age}</strong>\n· 배변 양상: <strong>${stool}</strong>\n· 구토 횟수/양상: <strong>${vomit}</strong>\n· 전신 활력: <strong>${vital}</strong></div>
    </div>

    <!-- SOAP [A] -->
    <div class="soap-box">
      <div class="soap-head">
        <span>[A] 수의 임상 추정 평가 (Assessment)</span>
        <span style="color:#c2410c;">진료실 우선 감별군</span>
      </div>
      <div class="soap-body" style="color:#991b1b; font-weight:700;">${assess}</div>
    </div>

    <!-- SOAP [P] -->
    <div class="soap-box">
      <div class="soap-head">
        <span>[P] 권장 처치 및 투약 계획 (Plan &amp; Rx)</span>
        <span style="color:#0d9488;">파보겔 공급처 프로토콜</span>
      </div>
      <div class="soap-body" style="color:#0f766e; font-weight:700;">${plan}</div>
    </div>

    <div class="callout">
      <strong>보호자 핵심 질문:</strong> ${q}
    </div>

    <div class="footer">
      <div>
        <strong>에스앤제이 동물병원</strong> (경기도 용인시 처인구 포곡읍 선장1로 98-8 봄봄솔루션 경매장 내)<br />
        유선 상담: 031-321-6562 / 긴급: 010-5407-5708
      </div>
      <div class="sign-area">
        <span>담당 수의사 확인:</span>
        <div class="sign-stamp">(서명/날인)</div>
      </div>
    </div>
  </div>
  <script>
    window.onload = function() {
      setTimeout(function() {
        window.print();
      }, 200);
    };
  <\/script>
</body>
</html>
  `;

  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('팝업이 차단되었습니다. 브라우저 팝업 차단을 해제 후 다시 시도해주세요.\n대신 요약서 텍스트 복사 기능을 이용해주세요.');
    return;
  }
  printWindow.document.open();
  printWindow.document.write(printHtml);
  printWindow.document.close();
  printWindow.focus();
}

function copySummaryText() {
  const pet = document.getElementById('summaryPetName').value || '미입력';
  const info = document.getElementById('summaryPetInfo').value || '미입력';
  const sym = document.getElementById('summarySymptoms').value || '특이 증상 없음';
  const q = document.getElementById('summaryQuestion').value || '특이 질문 없음';
  const risk = (window._lastSOAP && window._lastSOAP.riskDesc) || '3단계 경고 (ORANGE)';

  const summaryText = `[에스앤제이 동물병원 사전 문진 의뢰서]\n· 아이: ${pet} (${info})\n· 응급도: ${risk}\n· 주요 증상: ${sym}\n· 질문: ${q}\n· 내원/상담: 031-321-6562 (용인 봄봄솔루션 진료실)\n· 365일 온라인 문진: https://snj-vet.com`;
  
  if (navigator.clipboard && navigator.clipboard.writeText) {
    navigator.clipboard.writeText(summaryText).then(() => {
      alert('진료실 요약서가 클립보드에 복사되었습니다!\n카카오톡이나 문자 메시지로 바로 전송하실 수 있습니다.');
    }).catch(() => {
      alert('복사에 실패했습니다. 직접 복사해 주세요.');
    });
  }
}

// 13. DOM 로드 시 초기 이벤트 바인딩
document.addEventListener('DOMContentLoaded', function() {
  const symptomEl = document.getElementById('symptomText');
  if (symptomEl) {
    symptomEl.addEventListener('keydown', function(e) {
      if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') {
        e.preventDefault();
        runSmartTriage();
      }
    });
  }

  const btn = document.getElementById('mobileMenuBtn');
  if (btn) btn.addEventListener('click', toggleMobileMenu);

  document.addEventListener('click', function(e) {
    const nav = document.getElementById('mobileNav');
    const btnEl = document.getElementById('mobileMenuBtn');
    if (!nav || nav.hidden) return;
    if (!nav.contains(e.target) && e.target !== btnEl && !btnEl.contains(e.target)) {
      if (!e.target.classList.contains('modal-backdrop')) closeMobileMenu();
    }
  });

  ['summaryPetName', 'summaryPetInfo', 'summarySymptoms', 'summaryQuestion'].forEach(id => {
    const el = document.getElementById(id);
    if (el) el.addEventListener('input', syncChartPreview);
  });

  // 초기 상태 트리아지 및 차트 동기화
  syncChartPreview();
  calculateDosage();
});